# -*- coding: utf-8 -*-
"""ML_rec_system_Finall.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zwh93lk7sY9-9zv4irk0NU8yl9i5sM1s
"""

# pip install scikit-surprise

import pandas as pd
from surprise import Dataset, Reader, KNNBasic
from surprise.model_selection import train_test_split
from surprise import accuracy
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# #Read the CSV files into dataframes
# services = pd.read_csv('Services.csv',skipinitialspace=True)
# service_plan_names = pd.read_csv('Service_plan_names.csv',skipinitialspace=True)
# user_data = pd.read_csv('User.csv',skipinitialspace=True)
# user_subs_data = pd.read_csv('User_Subscriptions.csv',skipinitialspace=True)


import mysql.connector

# connection parameters
host = "localhost"
dbname = "ProSubscriber"
user = "root"
password = "admin"
port = "3306"

# establishing the connection
conn = mysql.connector.connect(
    host=host, database=dbname, user=user, password=password, port=port
)


def get_data():
    return pd.read_sql(
        f"SELECT u.email_address,u.gender,u.dob,u.is_student, us.plan_name,s.category, s.ratings, sp.* FROM user u, user_subscriptions us,services s, service_plans sp where u.email_address=us.email_address and us.service_name=s.service_name and s.service_name=sp.service_name",
        conn,
    )


df = get_data()

conn.close()

# df

from datetime import datetime

df["dob"] = pd.to_datetime(df["dob"])
# Calculate age from dob
current_date = datetime.now()
current_date = datetime.now()
df["Age"] = current_date.year - df["dob"].dt.year
# df

# adding column for age groups
age_groups = {"Young Adult": (18, 30), "Adult": (31, 50), "Senior": (51, float("inf"))}

df["Age Group"] = pd.cut(
    df["Age"],
    bins=[
        age_groups["Young Adult"][0],
        age_groups["Adult"][0],
        age_groups["Senior"][0],
        float("inf"),
    ],
    labels=["Young Adult", "Adult", "Senior"],
    right=False,
)

# df.head(20)

# df.to_csv('Merged_Data.csv')
# print(df[['email_address', 'service_name', 'ratings']].head())


reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(df[["email_address", "service_name", "ratings"]], reader)
trainset, testset = train_test_split(data, test_size=0.2, random_state=42)

# User-Based Collaborative Filtering
import pickle

sim_options = {"name": "cosine", "user_based": True}
algo = KNNBasic(sim_options=sim_options)

algo.fit(trainset)
predictions = algo.test(testset)
rmse = accuracy.rmse(predictions)

with open("knn_basic_model.pkl", "wb") as file:
    pickle.dump(algo, file)

# print(f'Root Mean Squared Error: {rmse}')

from surprise import Dataset, Reader
from surprise.model_selection import train_test_split
from surprise import SVD
from surprise import accuracy


reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(df[["email_address", "service_name", "ratings"]], reader)

trainset, testset = train_test_split(data, test_size=0.2, random_state=42)

model = SVD()
model.fit(trainset)

predictions = model.test(testset)

# Evaluating the model's performance
# accuracy.rmse(predictions)
with open("svd_model.pkl", "wb") as file:
    pickle.dump(model, file)


# Get top N recommendations for a specific user from the same category
def get_top_n_recommendations_surprise(model, email_address, category, n=3):
    # Get all subscriptions in the specified category
    category_subscriptions = df[df["category"] == category]["service_name"].unique()

    # Get subscriptions the user has not rated in the specified category
    user_rated_subscriptions = df[
        (df["email_address"] == email_address) & (df["category"] == category)
    ]["service_name"]
    user_unrated_subscriptions = list(
        set(category_subscriptions) - set(user_rated_subscriptions)
    )

    # Make predictions for unrated subscriptions
    unrated_predictions = [
        model.predict(email_address, subscription)
        for subscription in user_unrated_subscriptions
    ]

    # Sort predictions by estimated rating in descending order
    unrated_predictions.sort(key=lambda x: x.est, reverse=True)

    # Extract top N recommendations
    top_n_recommendations = unrated_predictions[:n]
    print(top_n_recommendations)

    # Return the subscription names and estimated ratings
    # print('top N recommendations  surprise: ',[{'Subscription': prediction.iid, 'Estimated Rating': prediction.est} for prediction in top_n_recommendations])
    return [
        {"service_name": prediction.iid, "Estimated Rating": prediction.est}
        for prediction in top_n_recommendations
    ]


# Example usage:
# email_address = 22
# category = 'Music'
# top_recommendations_surprise = get_top_n_recommendations_surprise(model, email_address, category, n=2)
# print('Collaborative Filtering Recommendations:', top_recommendations_surprise)

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer(stop_words="english")
tfidf_matrix = vectorizer.fit_transform(df["app_description"])


# Function to get top N content-based recommendations for a user
def get_content_based_recommendations(email_address, current_category, model, n=3):
    user_items = df[
        (df["email_address"] == email_address) & (df["category"] == current_category)
    ]["service_name"].tolist()

    user_tfidf_matrix = tfidf_matrix[df["service_name"].isin(user_items).values]

    if user_tfidf_matrix.shape[0] == 0:
        # If no subscriptions, return empty
        return []

    user_tfidf_vector = np.asarray(user_tfidf_matrix.mean(axis=0)).flatten()

    tfidf_matrix_array = np.asarray(tfidf_matrix.A)
    similarity_scores = cosine_similarity(
        user_tfidf_vector.reshape(1, -1), tfidf_matrix_array
    ).flatten()

    sorted_indices = similarity_scores.argsort()[::-1]

    # removin duplicates
    seen = set()
    unique_recommendations = [
        {
            "service_name": df.iloc[i]["service_name"],
            "Estimated Rating": similarity_scores[i] * 5,
        }
        for i in sorted_indices
        if not (
            df.iloc[i]["service_name"] in seen or seen.add(df.iloc[i]["service_name"])
        )
    ]

    top_recommendations = unique_recommendations[:n]
    # print('Top N content-based recommendations:', top_recommendations)
    return top_recommendations


# Function to compare pricing
def compare_pricing(sub_df, category, age, is_student):
    # print(sub_df.columns)

    # avoid settingwithcopywarnigg
    sub_pro = sub_df.copy()

    try:
        if is_student == 0:
            sub_pro = sub_pro.loc[
                (sub_pro["plan_name"] != "Student") & (sub_pro["category"] == category)
            ]
    except:
        sub_pro = sub_pro.loc[(sub_pro["category"] == category)]

    duration_mapping = {"Monthly": 1, "Quarterly": 3, "Half-yearly": 6, "Yearly": 12}
    sub_pro["Duration"] = sub_pro["payment_frequency"].map(duration_mapping)
    sub_pro["EquivalentMonthlyPrice"] = sub_pro["priceAED"] / sub_pro["Duration"]

    min_price_indices = sub_pro.groupby("service_name")[
        "EquivalentMonthlyPrice"
    ].idxmin()
    best_pricing = sub_pro.loc[
        min_price_indices,
        ["service_name", "plan_name", "EquivalentMonthlyPrice", "priceAED"],
    ].reset_index(drop=True)

    # print('compare pricing:',best_pricing.sort_values(by="EquivalentMonthlyPrice"))

    return best_pricing.sort_values(by="EquivalentMonthlyPrice")


# Function to find popular subscriptions in gender
def popular_in_gender(df, gender, category):
    new_df = df.loc[(df["gender"] == gender) & (df["category"] == category)]
    result_df = new_df.groupby("service_name").size().reset_index(name="Count")
    result_df = result_df.sort_values(by="Count", ascending=False)
    result_df["Count"] = (result_df["Count"] / (result_df["Count"].sum())) * 100
    result_df.rename(columns={"Count": "Score"}, inplace=True)
    # print('compare gender:',result_df)

    return result_df


# Function to find popular subscriptions in age group
def popular_in_ageGroup(df, ageGroup, category):
    new_df = df.loc[(df["Age Group"] == ageGroup) & (df["category"] == category)]
    result_df = new_df.groupby("service_name").size().reset_index(name="Count")
    result_df = result_df.sort_values(by="Count", ascending=False)
    result_df["Count"] = (result_df["Count"] / (result_df["Count"].sum())) * 100
    result_df.rename(columns={"Count": "Score"}, inplace=True)
    # print('compare age:',result_df)

    return result_df


# Function to recommend for a user segment
# Function to recommend for a user segment
def recommend_for_user_segment(email_address, current_category, model, algo, n=3):
    collaborative_recommendations = get_top_n_recommendations_surprise(
        model, email_address, current_category, n
    )
    content_based_recommendations = get_content_based_recommendations(
        email_address, current_category, algo, n
    )
    # print(df)
    user_data = df[
        (df["email_address"] == email_address) & (df["category"] == current_category)
    ].iloc[0]
    # print(user_data)

    pricing_recommendations = compare_pricing(
        df, current_category, user_data["Age"], user_data["is_student"]
    )

    gender_recommendations = popular_in_gender(
        df, user_data["gender"], current_category
    )

    age_group_recommendations = popular_in_ageGroup(
        df, user_data["Age Group"], current_category
    )

    pricing_plan_name = user_data.get("plan_name", None)

    # filtering the dataframe
    collaborative_recommendations = [
        rec
        for rec in collaborative_recommendations
        if "plan_name" not in rec
        or ("plan_name" in rec and rec["plan_name"] == pricing_plan_name)
    ]
    # print("collaborative_recommendations:",collaborative_recommendations)

    content_based_recommendations = [
        rec
        for rec in content_based_recommendations
        if "plan_name" not in rec
        or ("plan_name" in rec and rec["plan_name"] == pricing_plan_name)
    ]
    # print("content_based_recommendations:", content_based_recommendations)

    # print("pricing_recommendations:\n", pricing_recommendations)
    # print("gender_recommendations:\n", gender_recommendations)
    # print("age_group_recommendations:\n", age_group_recommendations)

    # Combining recommendations
    collaborative_df = pd.DataFrame(collaborative_recommendations)
    content_based_df = pd.DataFrame(content_based_recommendations)
    hybrid_df = collaborative_df.merge(
        content_based_df,
        on="service_name",
        how="outer",
        suffixes=("_collaborative", "_content_based"),
    )
    hybrid_df = hybrid_df.merge(
        pricing_recommendations,
        on="service_name",
        how="outer",
        suffixes=("", "_pricing"),
    )
    hybrid_df = hybrid_df.merge(
        gender_recommendations, on="service_name", how="outer", suffixes=("", "_gender")
    )
    hybrid_df = hybrid_df.merge(
        age_group_recommendations,
        on="service_name",
        how="outer",
        suffixes=("", "_age_group"),
    )

    # Convert the list of dictionaries to a DataFrame
    # hybrid_df = pd.DataFrame(hybrid_recommendations)

    # each row, find its score in pricing,gender,age, and then add onto the hybrid rec df a column stating advantages.
    # for example, if x is the current subscription, and y has a cheaper price, we add cheaper in the advantages column for row of y
    current_subscription_price = user_data.get("Price(AED)", 0)
    current_subscription = user_data.get("service_name")
    hybrid_df["advantages"] = "Similar"

    # removing repeated recommendations
    hybrid_df = hybrid_df.drop_duplicates(subset="service_name", keep="first")

    for index, row in hybrid_df.iterrows():
        # checking if its cheaper
        # print(row['EquivalentMonthlyPrice'], current_subscription_price)

        if (
            "EquivalentMonthlyPrice" in row
            and row["EquivalentMonthlyPrice"] < current_subscription_price
        ):
            hybrid_df.at[index, "advantages"] += ", Cheaper ({:.2f} AED/month)".format(
                row["EquivalentMonthlyPrice"]
            )

        if "service_name" in row and row["service_name"] in [
            "Youtube Music",
            "Spotify",
        ]:
            hybrid_df.at[index, "advantages"] += ", Offers Student plan_names"

        # checking the popularity
        try:
            current_sub_score_age = hybrid_df.loc[
                hybrid_df["service_name"] == current_subscription
            ]["Score_age_group"].unique()[0]
            current_sub_score_gender = hybrid_df.loc[
                hybrid_df["service_name"] == current_subscription
            ]["Score"].unique()[0]
            if (
                row["Score"] > current_sub_score_age
                or row["Score"] > current_sub_score_gender
            ):
                hybrid_df.at[index, "advantages"] += ", More popular in demographic"
        except:
            pass

    hybrid_df = hybrid_df[["service_name", "advantages"]]
    hybrid_df["email_address"] = email_address
    hybrid_df["category"] = current_category

    return hybrid_df.head(n)


# Example usage:
# email_address = "kvella@gmail.com"
# current_category = "Education"
# # print('Current Subscription that user '+ str(email_address) +' has: '+user_data['service_name']+'\n')

# print("\nTheir recommendations are:\n")
# recs = recommend_for_user_segment(email_address, current_category, model, algo, n=3)
# print(recs)


# # Example usage:
# email_address = 'lpearce0@squidoo.com'
# user_data = df[df['email_address'] == email_address].iloc[0]
# age_group, gender, current_category, is_student=user_data['Age Group'],user_data['gender'],user_data['category'],user_data['is_student']

# print('Current Subscription that user '+ str(email_address) +' has: '+user_data['service_name']+'\n')

# print('\nTheir recommendations are:\n')
# recs=recommend_for_user_segment(email_address, age_group, gender, current_category, is_student,model,algo, n=3)
# recs
